[package]
name = "bedwards/glassline"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[server-dependencies]
ProfileService = "etheroit/profileservice@1.2.0"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
